<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>dotnet2md</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="dotnet2md.tests" />
  </ItemGroup>

</Project>
